name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest-cov

      - name: Lint with flake8
        run: flake8 src scripts

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term-missing --maxfail=1 --disable-warnings -q

      - name: Build index on test docs
        run: |
          python -m scripts.parse_docs --input tests/fixtures/data_raw --output parsed/test.jsonl
          python -m scripts.embed_chunks --input parsed/test.jsonl --output embeddings/test.jsonl
          python -m scripts.build_faiss_index --embeddings embeddings/test.jsonl --index vector_store/test.index

      - name: Evaluate metrics
        run: python scripts/evaluate_retrieval.py --golden tests/fixtures/golden.json --index vector_store/test.index
